@echo off
netlify env:set "VITE_FIREBASE_API_KEY" "AIzaSyAXCdL20mO8fnDYU5_2ofn19COJCvzPQ4Y"
netlify env:set "VITE_FIREBASE_AUTH_DOMAIN" "fortheweebs-d6f24.firebaseapp.com"
netlify env:set "VITE_FIREBASE_PROJECT_ID" "fortheweebs-d6f24"
netlify env:set "VITE_FIREBASE_STORAGE_BUCKET" "fortheweebs-d6f24.firebasestorage.app"
netlify env:set "VITE_FIREBASE_MESSAGING_SENDER_ID" "1075224434953"
netlify env:set "VITE_FIREBASE_APP_ID" "1:1075224434953:web:f711b5deedbb9be2751bd8"
netlify env:set "VITE_STRIPE_PUBLISHABLE_KEY" "pk_live_51RyWwx4c1vlfw50BUVy6H3IM7eDsV5MJJqQWjvWQWQwzcccrQQMGuz094b6DKQcmzuH9CSDocvY51yDPqWsbRANh009IgZnOix"
netlify env:set "VITE_ADMIN_SECRET_KEY" "polotuspossumus_ftw_2025_owner"
netlify env:set "VITE_ADMIN_RECOVERY_PASSWORD" "jacobmorris_fortheweebs_owner_recovery_2025"
netlify env:set "VITE_ADMIN_USERNAME" "jacobmorris"
netlify env:set "VITE_ADMIN_PASSWORD" "polotuspossumus2025"
netlify env:set "VITE_OWNER_PHONE_NUMBER" "+12813819498"
netlify env:set "VITE_BACKUP_EMAIL" "jacob@fortheweebs.com"
netlify env:set "VITE_SECURITY_ANSWER_1" "jacob morris"
netlify env:set "VITE_SECURITY_ANSWER_2" "fortheweebs"
netlify env:set "VITE_SECURITY_ANSWER_3" "polotus possumus"
netlify env:set "VITE_API_BASE_URL" "https://fortheweebs.com/api"
