// Generates a sample output for a creator tool
export const generateCreatorOutput = (creatorId, tool) => ({
  creatorId,
  tool,
  outputType: 'content',
  content: `Generated by ${tool} for ${creatorId}`,
  profile: {
    campaigns: ['CGI Tribute', 'Legacy Drop'],
    monetization: '$12,400',
    badges: ['Founder', 'Sovereign Architect'],
  },
});
