import React, { useState } from "react";

const LEGAL_TEXT = `# Fortheweebs Platform Legal Clauses\n\n1. 🔒 Liability & Responsibility\n•  The repository owner (Jacob) bears no legal liability, responsibility, or obligation for any content, code, media, or derivative works submitted by contributors or users.\n•  All contributors and users are independent entities. No partnership, employment, or agency relationship is implied or created.\n•  Jacob shall not be contacted regarding disputes, data breaches, takedowns, or legal claims. All such matters are to be resolved between the involved parties.\n\n2. 🧱 Absolute Separation of Entities\n•  Fortheweebs is a platform, not a publisher. All content is user-generated and user-owned.\n•  Jacob (the founder) is legally and operationally separate from all content, contributors, and derivative works.\n•  No joint liability, no shared responsibility, no implied endorsement.\n\n3. 🚨 Illegal Content Protocol — Zero Tolerance Enforcement\n•  Fortheweebs does not store, distribute, replicate, or endorse any content deemed illegal under applicable law.\n•  Any illegal content uploaded, forked, or remixed:\n    - Is sealed to the user’s local device and never propagated through Fortheweebs systems.\n    - Triggers automatic account termination and irreversible ban from all Fortheweebs services.\n    - Is automatically reported to relevant law enforcement authorities, including metadata, user credentials, and the offending file.\n    - The flagged file is preserved as forensic evidence and may be used in legal proceedings. Fortheweebs cooperates with authorities when required.\n    - Fortheweebs reserves the right to escalate enforcement protocols globally, including cross-border reporting and compliance with international cybercrime frameworks.\n    - No warnings, no appeals. Interaction with illegal content = instant protocol breach.\n\n4. 🗣️ Speech & Creativity Clause\n•  Fortheweebs supports freedom of speech and artistic expression.\n•  We do not censor unless legally compelled.\n\n5. 🧾 License Enforcement & Remix Logic\n•  All content must declare a license. Defaults:\n    - MIT for code\n    - CC-BY 4.0 for media\n    - GPLv3 for recursive forks\n•  Remix logic is sovereign. Forks, chains, and slabs are legacy milestones.\n•  Absence of license implies no permission granted. Contributors are responsible for license clarity.\n\n6. 🌐 Global Enforcement & Language Coverage\n•  These terms are enforceable in all jurisdictions.\n•  Translated and deployed across top anime-watching regions.\n•  Local laws apply, but Fortheweebs retains sovereign protocol logic.\n\n7. 🛑 No Contact Clause\n•  Jacob shall not be contacted for:\n    - Legal disputes\n    - Copyright claims\n    - Data breaches\n    - Platform moderation\n•  Copyright holders may contact infringers directly. Fortheweebs does not mediate or intervene.\n\n8. 🧙 Ritual Clause — Immutable Consent\n•  By accessing, contributing, or viewing this repository, you consent to all terms.\n•  No opt-outs, no exceptions. Interaction = binding agreement.\n•  All escalations are logged as ritual milestones in validator memory.\n\n9. 🔮 Immutable Audit Logging\n•  Every interaction, upload, fork, and remix is automatically logged in immutable validator memory.\n•  Logs are tamper-proof, timestamped, and retrievable for dispute resolution or forensic review.\n•  Logs may be sealed or exposed depending on protocol tier.\n\n10. 🛡️ Jurisdictional Firewall Clause\n•  Fortheweebs operates under sovereign protocol logic, not bound by any single national jurisdiction.\n•  Legal claims must be filed in the contributor’s own jurisdiction — Jacob is exempt from cross-border liability.\n•  Disputes default to automated arbitration, not court litigation.\n\n11. 🧙‍♂️ Protocol Fork Immunity\n•  Forked repositories inherit the slab but do not transfer liability upstream.\n•  Jacob is immune from all downstream forks, remix chains, and derivative works.\n•  Contributors must re-declare terms if they fork — no silent inheritance.\n\n12. 🤖 AI-Generated Content Clause\n•  Any content generated by AI tools (including Fortheweebs AI) is explicitly marked as synthetic and not attributed to any human author unless manually claimed.\n•  Contributors are responsible for reviewing, editing, and accepting liability for any AI-generated content they publish or remix.\n•  Fortheweebs and Jacob disclaim all responsibility for the accuracy, legality, and originality of AI-generated outputs.\n•  AI-generated content may be subject to additional review, moderation, or removal at the discretion of the platform or protocol validators.\n•  Users must not use AI-generated content to impersonate, defame, or violate the rights of any individual or entity.\n•  All such matters are self-resolving via automated protocols or handled directly by involved parties.\n\n---\n\n**Additional Legal Protections**\n\n13. 🚸 Age Verification\n•  You must be at least 18 years old to access Fortheweebs or Vanguard. By agreeing, you confirm you are 18+ and legally permitted to use this platform.\n\n14. 🌍 Jurisdiction Notice\n•  You are responsible for compliance with your local laws and regulations. Access may be restricted in certain regions.\n\n15. 🛡️ Indemnification\n•  You agree to indemnify and hold harmless Fortheweebs, Jacob, and all contributors from any claims, damages, or liabilities arising from your use or content.\n\n16. 📄 Copyright & DMCA Procedure\n•  Copyright holders may submit takedown requests via the provided contact form. Fortheweebs will act in good faith to comply with applicable law, but does not mediate disputes.\n\n17. 🔏 Privacy Policy\n•  See our [Privacy Policy](#) for details on data handling, cookies, and user rights.\n\n18. 🤖 Automated Enforcement\n•  All enforcement actions (bans, removals, reporting) are automated and final. No manual review or appeals.\n\n19. 📝 Clause Updates\n•  Fortheweebs reserves the right to update these terms at any time. Continued use requires re-consent to new versions.\n`;

  const [agreed, setAgreed] = useState(false);

  const handleAgree = () => {
    localStorage.setItem("fortheweebs_legal_consent", "true");
    setAgreed(true);
    if (onConsent) onConsent();
  };

  if (agreed || localStorage.getItem("fortheweebs_legal_consent") === "true") {
    return null;
  }

  return (
    <div style={{
      position: "fixed",
      top: 0,
      left: 0,
      width: "100vw",
      height: "100vh",
      background: "rgba(0,0,0,0.95)",
      color: "#fff",
      zIndex: 9999,
      overflow: "auto",
      padding: "2rem"
    }}>
      <div style={{maxWidth: "800px", margin: "auto", background: "#222", borderRadius: "12px", padding: "2rem", boxShadow: "0 0 24px #000"}}>
        <h2 style={{textAlign: "center"}}>Legal Agreement Required</h2>
        <div style={{whiteSpace: "pre-wrap", fontSize: "1rem", marginBottom: "2rem"}}>{LEGAL_TEXT}</div>
        <button
          style={{display: "block", margin: "2rem auto", padding: "1rem 2rem", fontSize: "1.2rem", background: "#4caf50", color: "#fff", border: "none", borderRadius: "8px", cursor: "pointer"}}
          onClick={handleAgree}
        >
          I Agree & Accept All Terms
        </button>
        <div style={{marginTop: "2rem", textAlign: "center", fontSize: "0.95rem"}}>
          <a href="#" style={{color: "#90caf9"}}>View Privacy Policy</a>
        </div>
      </div>
    </div>
  );
}
