name: API Docs Sync

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Generate Swagger Docs
        run: node docs/generateDocs.js
      - name: Commit updated docs
        run: |
          git config --global user.name "Mico"
          git config --global user.email "mico@vanguard.local"
          git add docs/README.md
          git commit -m "Auto-update API docs"
          git push
