name: Build Electron App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build Electron app
        run: npm run build && npm run electron:package
      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: vanguard-${{ matrix.os }}
          path: release/
